../../material-properties/haiti_material_properties_douilly-2021.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
../../material-properties/haiti_material_properties_douilly-2021.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
../../material-properties/haiti_material_properties_douilly-2021.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
../../material-properties/haiti_material_properties_douilly-2021.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
../../material-properties/haiti_material_properties_douilly-2021.yaml: bad file
  what():  Error while parsing easi model file.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
../../material-properties/haiti_material_properties_douilly-2021.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
../../material-properties/haiti_material_properties_douilly-2021.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
../../material-properties/haiti_material_properties_douilly-2021.yaml: bad file
../../material-properties/haiti_material_properties_douilly-2021.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
  what():  Error while parsing easi model file.
../../material-properties/haiti_material_properties_douilly-2021.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
../../material-properties/haiti_material_properties_douilly-2021.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
../../material-properties/haiti_material_properties_douilly-2021.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
../../material-properties/haiti_material_properties_douilly-2021.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
../../material-properties/haiti_material_properties_douilly-2021.yaml: bad file
../../material-properties/haiti_material_properties_douilly-2021.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
  what():  Error while parsing easi model file.
../../material-properties/haiti_material_properties_douilly-2021.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
srun: error: i01r01c03s03: task 2: Aborted (core dumped)
srun: launch/slurm: _step_signal: Terminating StepId=3875117.0
srun: error: i01r01c03s06: task 5: Aborted (core dumped)
srun: error: i01r01c03s01: task 0: Aborted (core dumped)
srun: error: i01r01c03s11: task 10: Aborted (core dumped)
srun: error: i01r01c04s02: task 13: Aborted (core dumped)
srun: error: i01r01c03s07: task 6: Aborted (core dumped)
srun: error: i01r01c03s05: task 4: Aborted (core dumped)
srun: error: i01r01c04s01: task 12: Aborted (core dumped)
srun: error: i01r01c04s04: task 15: Aborted (core dumped)
srun: error: i01r01c03s04: task 3: Aborted (core dumped)
srun: error: i01r01c03s09: task 8: Aborted (core dumped)
srun: error: i01r01c03s12: task 11: Aborted (core dumped)
srun: error: i01r01c03s10: task 9: Aborted (core dumped)
srun: error: i01r01c04s03: task 14: Aborted (core dumped)
srun: error: i01r01c03s08: task 7: Aborted (core dumped)
srun: error: i01r01c03s02: task 1: Aborted (core dumped)
cp: cannot create directory '/hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs/regional-only/jobid_3875117/logs': No such file or directory
/var/spool/slurm/job3875117/slurm_script: line 80: pushd: /hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs/regional-only/jobid_3875117: No such file or directory
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/.local/bin/seissol_output_extractor", line 8, in <module>
    sys.exit(main())
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmfwriter/seissol_output_extractor.py", line 143, in main
    sx = SeissolxdmfExtended(args.xdmfFilename)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmf/seissolxdmf.py", line 14, in __init__
    with open (xdmfFilename, "r") as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'output-surface.xdmf'
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/soft/calc-moment-rate_supermuc.py", line 30, in find_xdmffile_wahweap
    xdmfFile = glob.glob(datadir + '*/jobid_'+jobid+'*/*extracted-fault.xdmf')[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/soft/calc-moment-rate_supermuc.py", line 211, in <module>
    generateMoment(jobid_list)
  File "/dss/dsshome1/01/di35poq/soft/calc-moment-rate_supermuc.py", line 87, in generateMoment
    xdmfFilename, momentCsvFile = find_xdmffile_wahweap(jobid)
  File "/dss/dsshome1/01/di35poq/soft/calc-moment-rate_supermuc.py", line 34, in find_xdmffile_wahweap
    xdmfFile = glob.glob(datadir + '*/jobid_'+jobid+'*/output-fault.xdmf')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/soft/calc-R-rake_supermuc.py", line 26, in find_xdmffile_wahweap
    xdmfFile = glob.glob(datadir + '*/jobid_'+jobid+'*/*extracted-fault.xdmf')[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/soft/calc-R-rake_supermuc.py", line 83, in <module>
    jobdir, xdmfFile, momentCsvFile = find_xdmffile_wahweap(jobid)
  File "/dss/dsshome1/01/di35poq/soft/calc-R-rake_supermuc.py", line 32, in find_xdmffile_wahweap
    xdmfFile = glob.glob(datadir + '*/jobid_'+jobid+'*/output-fault.xdmf')[0]
IndexError: list index out of range
[0m[31m(   4.262s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   4.262s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x1a4af10)
  Debug: Off
  Modified Time: 92784
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   4.262s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   4.262s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a3f2b0): Algorithm vtkXdmfReader (0x1a3c650) returned failure for request: vtkInformation (0x1a3e160)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   4.262s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   4.262s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a3f2b0): Algorithm vtkXdmfReader (0x1a3c650) returned failure for request: vtkInformation (0x1a3e160)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   4.263s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   4.263s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x1a4af10)
  Debug: Off
  Modified Time: 92784
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   4.263s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   4.263s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a3f2b0): Algorithm vtkXdmfReader (0x1a3c650) returned failure for request: vtkInformation (0x1a3e160)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   4.263s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   4.263s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a3f2b0): Algorithm vtkXdmfReader (0x1a3c650) returned failure for request: vtkInformation (0x1a3e160)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   4.265s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   4.265s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x1a4af10)
  Debug: Off
  Modified Time: 92784
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   4.265s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   4.265s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a3f2b0): Algorithm vtkXdmfReader (0x1a3c650) returned failure for request: vtkInformation (0x1a3e160)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   4.265s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   4.265s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a3f2b0): Algorithm vtkXdmfReader (0x1a3c650) returned failure for request: vtkInformation (0x1a3e160)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   4.973s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   4.973s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x335a810)
  Debug: Off
  Modified Time: 154809
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   4.973s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   4.973s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x335a810)
  Debug: Off
  Modified Time: 154809
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[33m(   5.154s) [paraview        ]vtkSMColorMapEditorHelp:772   WARN| Failed to determine the LookupTable being used.[0m
[0m[31m(   5.154s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   5.154s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x3ed8fa0)
  Debug: Off
  Modified Time: 878737
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   5.154s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x3e3e2c0): Algorithm vtkPVGeometryFilter (0x3fa4720) returned failure for request: vtkInformation (0x3e3f4b0)
  Debug: Off
  Modified Time: 878741
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   5.155s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   5.155s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x3dfc800)
  Debug: Off
  Modified Time: 878805
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   5.155s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x3e19a80): Algorithm vtkPVGeometryFilter (0x3dea3f0) returned failure for request: vtkInformation (0x3e1ab50)
  Debug: Off
  Modified Time: 878810
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   5.155s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   5.155s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x386f7d0)
  Debug: Off
  Modified Time: 878868
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   5.165s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x3e3e2c0): Algorithm vtkPVGeometryFilter (0x3fa4720) returned failure for request: vtkInformation (0x3e3f4b0)
  Debug: Off
  Modified Time: 878741
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   5.165s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x3e19a80): Algorithm vtkPVGeometryFilter (0x3dea3f0) returned failure for request: vtkInformation (0x3e1ab50)
  Debug: Off
  Modified Time: 878810
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[33m(   5.165s) [paraview        ]vtkSMColorMapEditorHelp:772   WARN| Failed to determine the LookupTable being used.[0m
[0m[31m(   5.165s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x3e3e2c0): Algorithm vtkPVGeometryFilter (0x3fa4720) returned failure for request: vtkInformation (0x3e3f4b0)
  Debug: Off
  Modified Time: 878741
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   5.165s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x3e19a80): Algorithm vtkPVGeometryFilter (0x3dea3f0) returned failure for request: vtkInformation (0x3e1ab50)
  Debug: Off
  Modified Time: 878810
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   5.170s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   5.170s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x47861e0)
  Debug: Off
  Modified Time: 882183
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   5.171s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   5.171s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x47afcf0)
  Debug: Off
  Modified Time: 882365
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   5.171s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   5.171s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x47afcf0)
  Debug: Off
  Modified Time: 882365
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   5.287s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   5.287s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x47afcf0)
  Debug: Off
  Modified Time: 882365
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   5.287s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   5.287s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x47afcf0)
  Debug: Off
  Modified Time: 882365
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[33m(   5.298s) [paraview        ]vtkSMColorMapEditorHelp:772   WARN| Failed to determine the LookupTable being used.[0m
[0m[33m(   5.304s) [paraview        ]vtkSMColorMapEditorHelp:170   WARN| Could not determine array range.[0m
[0m[33m(   5.304s) [paraview        ]vtkSMColorMapEditorHelp:170   WARN| Could not determine array range.[0m
[0m[31m(   5.315s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   5.315s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x5695ab0)
  Debug: Off
  Modified Time: 1029688
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   5.316s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   5.316s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x5696cb0)
  Debug: Off
  Modified Time: 1029870
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   5.316s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   5.316s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x5696cb0)
  Debug: Off
  Modified Time: 1029870
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   5.428s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   5.428s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x5696cb0)
  Debug: Off
  Modified Time: 1029870
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   5.429s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   5.429s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x5696cb0)
  Debug: Off
  Modified Time: 1029870
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   5.439s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   5.439s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x5696cb0)
  Debug: Off
  Modified Time: 1029870
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   5.439s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   5.439s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x5696cb0)
  Debug: Off
  Modified Time: 1029870
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   5.443s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   5.443s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x6248520)
  Debug: Off
  Modified Time: 1171886
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   5.443s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x1a3c650): Error opening file output_jobid_3875117_extracted-fault.xdmf[0m
[0m[31m(   5.443s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x1a4b920): Algorithm vtkFileSeriesReader (0x1a49390) returned failure for request: vtkInformation (0x6248520)
  Debug: Off
  Modified Time: 1171886
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/soft/plot_initial_stress_profile.py", line 58, in <module>
    data = pd.read_csv(csvfile)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 557, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
/var/spool/slurm/job3875117/slurm_script: line 95: popd: directory stack empty
cp: target '/hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs/regional-only/jobid_3875117/logs/' is not a directory
