Error running function f [string "function f (x)..."]:13: attempt to compare nil with number
Error running function f [string "function f (x)..."]:13: attempt to compare nil with number
srun: error: i01r01c04s01: task 12: Aborted (core dumped)
srun: launch/slurm: _step_signal: Terminating StepId=3933050.0
slurmstepd: error: *** STEP 3933050.0 ON i01r01c03s01 CANCELLED AT 2024-09-26T00:27:01 ***
srun: error: i01r01c04s02: task 13: Aborted (core dumped)
srun: error: i01r01c03s12: task 11: Terminated
srun: error: i01r01c03s08: task 7: Terminated
srun: error: i01r01c03s03: task 2: Terminated
srun: error: i01r01c04s03: task 14: Terminated
srun: error: i01r01c03s07: task 6: Terminated
srun: error: i01r01c03s06: task 5: Terminated
srun: error: i01r01c03s09: task 8: Terminated
srun: error: i01r01c03s02: task 1: Terminated
srun: error: i01r01c03s10: task 9: Terminated
srun: error: i01r01c04s04: task 15: Terminated
srun: error: i01r01c03s01: task 0: Terminated
srun: error: i01r01c03s05: task 4: Terminated
srun: error: i01r01c03s04: task 3: Terminated
srun: error: i01r01c03s11: task 10: Terminated
srun: Force Terminated StepId=3933050.0
cp: cannot create directory '/hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs/variable_SH_max/jobid_3933050/logs': No such file or directory
/var/spool/slurm/job3933050/slurm_script: line 80: pushd: /hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs/variable_SH_max/jobid_3933050: No such file or directory
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/.local/bin/seissol_output_extractor", line 8, in <module>
    sys.exit(main())
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmfwriter/seissol_output_extractor.py", line 143, in main
    sx = SeissolxdmfExtended(args.xdmfFilename)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmf/seissolxdmf.py", line 14, in __init__
    with open (xdmfFilename, "r") as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'output-surface.xdmf'
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/soft/calc-moment-rate_supermuc.py", line 30, in find_xdmffile_wahweap
    xdmfFile = glob.glob(datadir + '*/jobid_'+jobid+'*/*extracted-fault.xdmf')[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/soft/calc-moment-rate_supermuc.py", line 211, in <module>
    generateMoment(jobid_list)
  File "/dss/dsshome1/01/di35poq/soft/calc-moment-rate_supermuc.py", line 87, in generateMoment
    xdmfFilename, momentCsvFile = find_xdmffile_wahweap(jobid)
  File "/dss/dsshome1/01/di35poq/soft/calc-moment-rate_supermuc.py", line 34, in find_xdmffile_wahweap
    xdmfFile = glob.glob(datadir + '*/jobid_'+jobid+'*/output-fault.xdmf')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/soft/calc-R-rake_supermuc.py", line 83, in <module>
    jobdir, xdmfFile, momentCsvFile = find_xdmffile_wahweap(jobid)
  File "/dss/dsshome1/01/di35poq/soft/calc-R-rake_supermuc.py", line 32, in find_xdmffile_wahweap
    xdmfFile = glob.glob(datadir + '*/jobid_'+jobid+'*/output-fault.xdmf')[0]
IndexError: list index out of range
[0m[31m(   1.668s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   1.672s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x2a4ce10)
  Debug: Off
  Modified Time: 92784
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.673s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   1.675s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a411b0): Algorithm vtkXdmfReader (0x2a3e550) returned failure for request: vtkInformation (0x2a40060)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.675s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   1.675s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a411b0): Algorithm vtkXdmfReader (0x2a3e550) returned failure for request: vtkInformation (0x2a40060)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.675s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   1.675s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x2a4ce10)
  Debug: Off
  Modified Time: 92784
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.675s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   1.675s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a411b0): Algorithm vtkXdmfReader (0x2a3e550) returned failure for request: vtkInformation (0x2a40060)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.675s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   1.675s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a411b0): Algorithm vtkXdmfReader (0x2a3e550) returned failure for request: vtkInformation (0x2a40060)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.677s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   1.677s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x2a4ce10)
  Debug: Off
  Modified Time: 92784
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.677s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   1.677s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a411b0): Algorithm vtkXdmfReader (0x2a3e550) returned failure for request: vtkInformation (0x2a40060)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.677s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   1.677s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a411b0): Algorithm vtkXdmfReader (0x2a3e550) returned failure for request: vtkInformation (0x2a40060)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.773s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   1.773s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x435d100)
  Debug: Off
  Modified Time: 154810
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.773s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   1.773s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x435d100)
  Debug: Off
  Modified Time: 154810
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[33m(   1.917s) [paraview        ]vtkSMColorMapEditorHelp:772   WARN| Failed to determine the LookupTable being used.[0m
[0m[31m(   1.918s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   1.918s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x4edba30)
  Debug: Off
  Modified Time: 878735
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.918s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x4f21990): Algorithm vtkPVGeometryFilter (0x4fa7060) returned failure for request: vtkInformation (0x4e41d80)
  Debug: Off
  Modified Time: 878739
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.918s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   1.918s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x4dff140)
  Debug: Off
  Modified Time: 878803
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.918s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x4e1c3c0): Algorithm vtkPVGeometryFilter (0x4decd30) returned failure for request: vtkInformation (0x4e1d490)
  Debug: Off
  Modified Time: 878808
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.918s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   1.918s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x4871fa0)
  Debug: Off
  Modified Time: 878866
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.927s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x4f21990): Algorithm vtkPVGeometryFilter (0x4fa7060) returned failure for request: vtkInformation (0x4e41d80)
  Debug: Off
  Modified Time: 878739
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.927s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x4e1c3c0): Algorithm vtkPVGeometryFilter (0x4decd30) returned failure for request: vtkInformation (0x4e1d490)
  Debug: Off
  Modified Time: 878808
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[33m(   1.927s) [paraview        ]vtkSMColorMapEditorHelp:772   WARN| Failed to determine the LookupTable being used.[0m
[0m[31m(   1.927s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x4f21990): Algorithm vtkPVGeometryFilter (0x4fa7060) returned failure for request: vtkInformation (0x4e41d80)
  Debug: Off
  Modified Time: 878739
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.927s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x4e1c3c0): Algorithm vtkPVGeometryFilter (0x4decd30) returned failure for request: vtkInformation (0x4e1d490)
  Debug: Off
  Modified Time: 878808
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.932s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   1.933s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x57892d0)
  Debug: Off
  Modified Time: 882182
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.933s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   1.933s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x57b2de0)
  Debug: Off
  Modified Time: 882364
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.933s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   1.933s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x57b2de0)
  Debug: Off
  Modified Time: 882364
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.049s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   2.049s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x57b2de0)
  Debug: Off
  Modified Time: 882364
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.049s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   2.049s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x57b2de0)
  Debug: Off
  Modified Time: 882364
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[33m(   2.059s) [paraview        ]vtkSMColorMapEditorHelp:772   WARN| Failed to determine the LookupTable being used.[0m
[0m[33m(   2.065s) [paraview        ]vtkSMColorMapEditorHelp:170   WARN| Could not determine array range.[0m
[0m[33m(   2.065s) [paraview        ]vtkSMColorMapEditorHelp:170   WARN| Could not determine array range.[0m
[0m[31m(   2.076s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   2.076s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x6783540)
  Debug: Off
  Modified Time: 1029681
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.077s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   2.077s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x66a1900)
  Debug: Off
  Modified Time: 1029863
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.077s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   2.077s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x66a1900)
  Debug: Off
  Modified Time: 1029863
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.189s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   2.189s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x66a1900)
  Debug: Off
  Modified Time: 1029863
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.189s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   2.189s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x66a1900)
  Debug: Off
  Modified Time: 1029863
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.200s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   2.200s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x66a1900)
  Debug: Off
  Modified Time: 1029863
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.200s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   2.200s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x66a1900)
  Debug: Off
  Modified Time: 1029863
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.203s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   2.203s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x6557620)
  Debug: Off
  Modified Time: 1171877
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.203s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2a3e550): Error opening file output_jobid_3933050_extracted-fault.xdmf[0m
[0m[31m(   2.203s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2a4d820): Algorithm vtkFileSeriesReader (0x2a4b290) returned failure for request: vtkInformation (0x6557620)
  Debug: Off
  Modified Time: 1171877
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/soft/plot_initial_stress_profile.py", line 58, in <module>
    data = pd.read_csv(csvfile)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 557, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
/var/spool/slurm/job3933050/slurm_script: line 95: popd: directory stack empty
cp: target '/hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs/variable_SH_max/jobid_3933050/logs/' is not a directory
