Haiti_sig_zz.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
Haiti_sig_zz.yaml: bad file
Haiti_sig_zz.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
Haiti_sig_zz.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
Haiti_sig_zz.yaml: bad file
Haiti_sig_zz.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
Haiti_sig_zz.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
Haiti_sig_zz.yaml: bad file
Haiti_sig_zz.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
Haiti_sig_zz.yaml: bad file
Haiti_sig_zz.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
  what():  Error while parsing easi model file.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
Haiti_sig_zz.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
Haiti_sig_zz.yaml: bad file
  what():  Error while parsing easi model file.
terminate called after throwing an instance of 'std::runtime_error'
Haiti_sig_zz.yaml: bad file
  what():  Error while parsing easi model file.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
Haiti_sig_zz.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
Haiti_sig_zz.yaml: bad file
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
srun: error: i01r01c03s04: task 3: Aborted (core dumped)
srun: launch/slurm: _step_signal: Terminating StepId=3932349.0
srun: error: i01r01c04s04: task 15: Aborted (core dumped)
srun: error: i01r01c03s11: task 10: Aborted (core dumped)
srun: error: i01r01c03s02: task 1: Aborted (core dumped)
srun: error: i01r01c03s10: task 9: Aborted (core dumped)
srun: error: i01r01c03s05: task 4: Aborted (core dumped)
srun: error: i01r01c03s07: task 6: Aborted (core dumped)
srun: error: i01r01c03s08: task 7: Aborted (core dumped)
srun: error: i01r01c04s02: task 13: Aborted (core dumped)
srun: error: i01r01c03s09: task 8: Aborted (core dumped)
srun: error: i01r01c03s03: task 2: Aborted (core dumped)
srun: error: i01r01c03s01: task 0: Aborted (core dumped)
srun: error: i01r01c03s12: task 11: Aborted (core dumped)
srun: error: i01r01c04s03: task 14: Aborted (core dumped)
srun: error: i01r01c03s06: task 5: Aborted (core dumped)
srun: error: i01r01c04s01: task 12: Aborted (core dumped)
cp: cannot create directory '/hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs/variable_SH_max/jobid_3932349/logs': No such file or directory
/var/spool/slurm/job3932349/slurm_script: line 80: pushd: /hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs/variable_SH_max/jobid_3932349: No such file or directory
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/.local/bin/seissol_output_extractor", line 8, in <module>
    sys.exit(main())
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmfwriter/seissol_output_extractor.py", line 143, in main
    sx = SeissolxdmfExtended(args.xdmfFilename)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmf/seissolxdmf.py", line 14, in __init__
    with open (xdmfFilename, "r") as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'output-surface.xdmf'
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/soft/calc-moment-rate_supermuc.py", line 30, in find_xdmffile_wahweap
    xdmfFile = glob.glob(datadir + '*/jobid_'+jobid+'*/*extracted-fault.xdmf')[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/soft/calc-moment-rate_supermuc.py", line 211, in <module>
    generateMoment(jobid_list)
  File "/dss/dsshome1/01/di35poq/soft/calc-moment-rate_supermuc.py", line 87, in generateMoment
    xdmfFilename, momentCsvFile = find_xdmffile_wahweap(jobid)
  File "/dss/dsshome1/01/di35poq/soft/calc-moment-rate_supermuc.py", line 34, in find_xdmffile_wahweap
    xdmfFile = glob.glob(datadir + '*/jobid_'+jobid+'*/output-fault.xdmf')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/soft/calc-R-rake_supermuc.py", line 83, in <module>
    jobdir, xdmfFile, momentCsvFile = find_xdmffile_wahweap(jobid)
  File "/dss/dsshome1/01/di35poq/soft/calc-R-rake_supermuc.py", line 32, in find_xdmffile_wahweap
    xdmfFile = glob.glob(datadir + '*/jobid_'+jobid+'*/output-fault.xdmf')[0]
IndexError: list index out of range
[0m[31m(   1.955s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   1.955s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x2310580)
  Debug: Off
  Modified Time: 92784
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.955s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   1.955s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2304920): Algorithm vtkXdmfReader (0x2301cc0) returned failure for request: vtkInformation (0x23037d0)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.955s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   1.956s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2304920): Algorithm vtkXdmfReader (0x2301cc0) returned failure for request: vtkInformation (0x23037d0)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.956s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   1.956s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x2310580)
  Debug: Off
  Modified Time: 92784
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.956s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   1.956s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2304920): Algorithm vtkXdmfReader (0x2301cc0) returned failure for request: vtkInformation (0x23037d0)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.956s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   1.956s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2304920): Algorithm vtkXdmfReader (0x2301cc0) returned failure for request: vtkInformation (0x23037d0)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.958s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   1.958s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x2310580)
  Debug: Off
  Modified Time: 92784
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.958s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   1.958s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2304920): Algorithm vtkXdmfReader (0x2301cc0) returned failure for request: vtkInformation (0x23037d0)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.958s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   1.958s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2304920): Algorithm vtkXdmfReader (0x2301cc0) returned failure for request: vtkInformation (0x23037d0)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.087s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   2.087s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x3c20a30)
  Debug: Off
  Modified Time: 154810
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.087s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   2.087s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x3c20a30)
  Debug: Off
  Modified Time: 154810
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[33m(   2.264s) [paraview        ]vtkSMColorMapEditorHelp:772   WARN| Failed to determine the LookupTable being used.[0m
[0m[31m(   2.265s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   2.265s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x47977b0)
  Debug: Off
  Modified Time: 878736
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.265s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x47e5310): Algorithm vtkPVGeometryFilter (0x486a9b0) returned failure for request: vtkInformation (0x47056e0)
  Debug: Off
  Modified Time: 878740
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.265s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   2.265s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x46c2aa0)
  Debug: Off
  Modified Time: 878804
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.265s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x46dfd20): Algorithm vtkPVGeometryFilter (0x46b0690) returned failure for request: vtkInformation (0x46e0df0)
  Debug: Off
  Modified Time: 878809
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.265s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   2.265s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x41358e0)
  Debug: Off
  Modified Time: 878867
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.274s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x47e5310): Algorithm vtkPVGeometryFilter (0x486a9b0) returned failure for request: vtkInformation (0x47056e0)
  Debug: Off
  Modified Time: 878740
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.274s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x46dfd20): Algorithm vtkPVGeometryFilter (0x46b0690) returned failure for request: vtkInformation (0x46e0df0)
  Debug: Off
  Modified Time: 878809
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[33m(   2.274s) [paraview        ]vtkSMColorMapEditorHelp:772   WARN| Failed to determine the LookupTable being used.[0m
[0m[31m(   2.274s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x47e5310): Algorithm vtkPVGeometryFilter (0x486a9b0) returned failure for request: vtkInformation (0x47056e0)
  Debug: Off
  Modified Time: 878740
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.274s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x46dfd20): Algorithm vtkPVGeometryFilter (0x46b0690) returned failure for request: vtkInformation (0x46e0df0)
  Debug: Off
  Modified Time: 878809
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.279s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   2.279s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x504ca70)
  Debug: Off
  Modified Time: 882183
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.280s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   2.280s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x5076580)
  Debug: Off
  Modified Time: 882365
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.280s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   2.280s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x5076580)
  Debug: Off
  Modified Time: 882365
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.396s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   2.396s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x5076580)
  Debug: Off
  Modified Time: 882365
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.396s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   2.396s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x5076580)
  Debug: Off
  Modified Time: 882365
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[33m(   2.407s) [paraview        ]vtkSMColorMapEditorHelp:772   WARN| Failed to determine the LookupTable being used.[0m
[0m[33m(   2.413s) [paraview        ]vtkSMColorMapEditorHelp:170   WARN| Could not determine array range.[0m
[0m[33m(   2.413s) [paraview        ]vtkSMColorMapEditorHelp:170   WARN| Could not determine array range.[0m
[0m[31m(   2.424s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   2.424s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x6046430)
  Debug: Off
  Modified Time: 1029685
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.425s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   2.425s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x5f5a740)
  Debug: Off
  Modified Time: 1029867
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.425s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   2.425s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x5f5a740)
  Debug: Off
  Modified Time: 1029867
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.537s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   2.537s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x5f5a740)
  Debug: Off
  Modified Time: 1029867
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.537s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   2.537s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x5f5a740)
  Debug: Off
  Modified Time: 1029867
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.548s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   2.548s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x5f5a740)
  Debug: Off
  Modified Time: 1029867
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.548s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   2.548s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x5f5a740)
  Debug: Off
  Modified Time: 1029867
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.551s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   2.551s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x50112f0)
  Debug: Off
  Modified Time: 1171882
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.551s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x2301cc0): Error opening file output_jobid_3932349_extracted-fault.xdmf[0m
[0m[31m(   2.551s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2310f90): Algorithm vtkFileSeriesReader (0x230ea00) returned failure for request: vtkInformation (0x50112f0)
  Debug: Off
  Modified Time: 1171882
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/soft/plot_initial_stress_profile.py", line 58, in <module>
    data = pd.read_csv(csvfile)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 557, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
/var/spool/slurm/job3932349/slurm_script: line 95: popd: directory stack empty
cp: target '/hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs/variable_SH_max/jobid_3932349/logs/' is not a directory
