srun: error: i01r01c04s04: task 15: Segmentation fault (core dumped)
srun: launch/slurm: _step_signal: Terminating StepId=4051085.0
srun: error: i01r01c03s08: task 7: Segmentation fault (core dumped)
srun: error: i01r01c04s01: task 12: Segmentation fault (core dumped)
srun: error: i01r01c03s07: task 6: Segmentation fault (core dumped)
srun: error: i01r01c03s04: task 3: Segmentation fault (core dumped)
srun: error: i01r01c03s12: task 11: Segmentation fault (core dumped)
srun: error: i01r01c03s05: task 4: Segmentation fault (core dumped)
srun: error: i01r01c03s06: task 5: Segmentation fault (core dumped)
srun: error: i01r01c03s02: task 1: Segmentation fault (core dumped)
srun: error: i01r01c03s01: task 0: Segmentation fault (core dumped)
srun: error: i01r01c04s03: task 14: Segmentation fault (core dumped)
srun: error: i01r01c03s11: task 10: Segmentation fault (core dumped)
srun: error: i01r01c03s10: task 9: Segmentation fault (core dumped)
srun: error: i01r01c04s02: task 13: Segmentation fault (core dumped)
srun: error: i01r01c03s09: task 8: Segmentation fault (core dumped)
srun: error: i01r01c03s03: task 2: Segmentation fault (core dumped)
cp: cannot create directory '/hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs/variable_SH_max/jobid_4051085/logs': No such file or directory
/var/spool/slurm/job4051085/slurm_script: line 80: pushd: /hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs/variable_SH_max/jobid_4051085: No such file or directory
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/.local/bin/seissol_output_extractor", line 8, in <module>
    sys.exit(main())
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmfwriter/seissol_output_extractor.py", line 143, in main
    sx = SeissolxdmfExtended(args.xdmfFilename)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmf/seissolxdmf.py", line 14, in __init__
    with open (xdmfFilename, "r") as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'output-surface.xdmf'
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/soft/calc-moment-rate_supermuc.py", line 30, in find_xdmffile_wahweap
    xdmfFile = glob.glob(datadir + '*/jobid_'+jobid+'*/*extracted-fault.xdmf')[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/soft/calc-moment-rate_supermuc.py", line 209, in <module>
    generateMoment(jobid_list)
  File "/dss/dsshome1/01/di35poq/soft/calc-moment-rate_supermuc.py", line 85, in generateMoment
    xdmfFilename, momentCsvFile = find_xdmffile_wahweap(jobid)
  File "/dss/dsshome1/01/di35poq/soft/calc-moment-rate_supermuc.py", line 34, in find_xdmffile_wahweap
    xdmfFile = glob.glob(datadir + '*/jobid_'+jobid+'*/output-fault.xdmf')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/soft/calc-R-rake_supermuc.py", line 83, in <module>
    jobdir, xdmfFile, momentCsvFile = find_xdmffile_wahweap(jobid)
  File "/dss/dsshome1/01/di35poq/soft/calc-R-rake_supermuc.py", line 32, in find_xdmffile_wahweap
    xdmfFile = glob.glob(datadir + '*/jobid_'+jobid+'*/output-fault.xdmf')[0]
IndexError: list index out of range
[0m[31m(   1.667s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   1.667s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x264e570)
  Debug: Off
  Modified Time: 92784
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.667s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   1.668s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2642720): Algorithm vtkXdmfReader (0x263fac0) returned failure for request: vtkInformation (0x26415d0)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.668s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   1.668s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2642720): Algorithm vtkXdmfReader (0x263fac0) returned failure for request: vtkInformation (0x26415d0)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.668s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   1.668s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x264e570)
  Debug: Off
  Modified Time: 92784
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.668s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   1.668s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2642720): Algorithm vtkXdmfReader (0x263fac0) returned failure for request: vtkInformation (0x26415d0)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.669s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   1.669s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2642720): Algorithm vtkXdmfReader (0x263fac0) returned failure for request: vtkInformation (0x26415d0)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.670s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   1.671s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x264e570)
  Debug: Off
  Modified Time: 92784
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.671s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   1.671s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2642720): Algorithm vtkXdmfReader (0x263fac0) returned failure for request: vtkInformation (0x26415d0)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.671s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   1.671s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x2642720): Algorithm vtkXdmfReader (0x263fac0) returned failure for request: vtkInformation (0x26415d0)
  Debug: Off
  Modified Time: 92671
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.768s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   1.768s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x3f5e030)
  Debug: Off
  Modified Time: 154811
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.768s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   1.768s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x3f5e030)
  Debug: Off
  Modified Time: 154811
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[33m(   1.912s) [paraview        ]vtkSMColorMapEditorHelp:772   WARN| Failed to determine the LookupTable being used.[0m
[0m[31m(   1.913s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   1.913s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x4adc940)
  Debug: Off
  Modified Time: 878736
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.913s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x4a41e40): Algorithm vtkPVGeometryFilter (0x4ba7f90) returned failure for request: vtkInformation (0x4a52480)
  Debug: Off
  Modified Time: 878740
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.913s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   1.914s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x4a00050)
  Debug: Off
  Modified Time: 878804
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.914s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x4a1d2d0): Algorithm vtkPVGeometryFilter (0x49edc40) returned failure for request: vtkInformation (0x4a1e3a0)
  Debug: Off
  Modified Time: 878809
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.914s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   1.914s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x4472eb0)
  Debug: Off
  Modified Time: 878867
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.922s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x4a41e40): Algorithm vtkPVGeometryFilter (0x4ba7f90) returned failure for request: vtkInformation (0x4a52480)
  Debug: Off
  Modified Time: 878740
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.923s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x4a1d2d0): Algorithm vtkPVGeometryFilter (0x49edc40) returned failure for request: vtkInformation (0x4a1e3a0)
  Debug: Off
  Modified Time: 878809
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[33m(   1.923s) [paraview        ]vtkSMColorMapEditorHelp:772   WARN| Failed to determine the LookupTable being used.[0m
[0m[31m(   1.923s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x4a41e40): Algorithm vtkPVGeometryFilter (0x4ba7f90) returned failure for request: vtkInformation (0x4a52480)
  Debug: Off
  Modified Time: 878740
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.923s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkCompositeDataPipeline (0x4a1d2d0): Algorithm vtkPVGeometryFilter (0x49edc40) returned failure for request: vtkInformation (0x4a1e3a0)
  Debug: Off
  Modified Time: 878809
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.928s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   1.928s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x5389cf0)
  Debug: Off
  Modified Time: 882183
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.929s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   1.929s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x53b3800)
  Debug: Off
  Modified Time: 882365
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   1.929s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   1.929s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x53b3800)
  Debug: Off
  Modified Time: 882365
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.046s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   2.046s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x53b3800)
  Debug: Off
  Modified Time: 882365
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.046s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   2.046s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x53b3800)
  Debug: Off
  Modified Time: 882365
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[33m(   2.056s) [paraview        ]vtkSMColorMapEditorHelp:772   WARN| Failed to determine the LookupTable being used.[0m
[0m[33m(   2.063s) [paraview        ]vtkSMColorMapEditorHelp:170   WARN| Could not determine array range.[0m
[0m[33m(   2.063s) [paraview        ]vtkSMColorMapEditorHelp:170   WARN| Could not determine array range.[0m
[0m[31m(   2.074s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   2.074s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x623f0a0)
  Debug: Off
  Modified Time: 1029682
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.075s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   2.075s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x62a1f30)
  Debug: Off
  Modified Time: 1029864
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.075s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   2.075s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x62a1f30)
  Debug: Off
  Modified Time: 1029864
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.188s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   2.188s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x62a1f30)
  Debug: Off
  Modified Time: 1029864
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.188s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   2.188s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x62a1f30)
  Debug: Off
  Modified Time: 1029864
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.199s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   2.199s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x62a1f30)
  Debug: Off
  Modified Time: 1029864
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.199s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   2.199s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x62a1f30)
  Debug: Off
  Modified Time: 1029864
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.203s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   2.203s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x5e4c7a0)
  Debug: Off
  Modified Time: 1171878
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
[0m[31m(   2.203s) [paraview        ]      vtkXdmfReader.cxx:253    ERR| vtkXdmfReader (0x263fac0): Error opening file output_jobid_4051085_extracted-fault.xdmf[0m
[0m[31m(   2.203s) [paraview        ]       vtkExecutive.cxx:729    ERR| vtkPVCompositeDataPipeline (0x264ef80): Algorithm vtkFileSeriesReader (0x264c9f0) returned failure for request: vtkInformation (0x5e4c7a0)
  Debug: Off
  Modified Time: 1171878
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

[0m
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/soft/plot_initial_stress_profile.py", line 58, in <module>
    data = pd.read_csv(csvfile)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 557, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
/var/spool/slurm/job4051085/slurm_script: line 95: popd: directory stack empty
cp: target '/hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs/variable_SH_max/jobid_4051085/logs/' is not a directory
