Couldn't load script: [string "function f (x)..."]:4: '}' expected (to close '{' at line 2) near 'sig_zz'Couldn't load script: [string "function f (x)..."]:4: '}' expected (to close '{' at line 2) near 'sig_zz'srun: error: i03r11c04s01: task 8: Aborted (core dumped)
srun: launch/slurm: _step_signal: Terminating StepId=3460100.0
slurmstepd: error: *** STEP 3460100.0 ON i03r11c03s05 CANCELLED AT 2024-07-24T19:38:48 ***
srun: error: i03r11c05s09: task 9: Aborted (core dumped)
srun: error: i03r11c03s09: task 4: Terminated
srun: error: i03r11c05s12: task 11: Terminated
srun: error: i03r11c03s07: task 2: Terminated
srun: error: i03r11c05s10: task 10: Terminated
srun: error: i03r11c06s05: task 15: Terminated
srun: error: i03r11c03s06: task 1: Terminated
srun: error: i03r11c06s02: task 13: Terminated
srun: error: i03r11c03s11: task 6: Terminated
srun: error: i03r11c03s08: task 3: Terminated
srun: error: i03r11c03s10: task 5: Terminated
srun: error: i03r11c06s04: task 14: Terminated
srun: error: i03r11c03s05: task 0: Terminated
srun: error: i03r11c06s01: task 12: Terminated
srun: error: i03r11c03s12: task 7: Terminated
srun: Force Terminated StepId=3460100.0
/var/spool/slurm/job3460100/slurm_script: line 66: pushd: /hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs/outputs_tmp: No such file or directory
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/.local/bin/seissol_output_extractor", line 8, in <module>
    sys.exit(main())
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmfwriter/seissol_output_extractor.py", line 143, in main
    sx = SeissolxdmfExtended(args.xdmfFilename)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmf/seissolxdmf.py", line 14, in __init__
    with open (xdmfFilename, "r") as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'output-fault.xdmf'
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/.local/bin/seissol_output_extractor", line 8, in <module>
    sys.exit(main())
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmfwriter/seissol_output_extractor.py", line 143, in main
    sx = SeissolxdmfExtended(args.xdmfFilename)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmf/seissolxdmf.py", line 14, in __init__
    with open (xdmfFilename, "r") as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'output-surface.xdmf'
/var/spool/slurm/job3460100/slurm_script: line 72: popd: directory stack empty
mv: cannot stat '/hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs/outputs_tmp': No such file or directory
cp: cannot create directory '/hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs/regional-only/jobid_3460100/logs': No such file or directory
